# Generated by Django 3.2.19 on 2023-06-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='county',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
