# Generated by Django 3.2.19 on 2023-06-10 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('session_bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=250, null=True, unique=True),
        ),
    ]
