# Generated by Django 3.2.19 on 2023-06-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_bookings', '0003_auto_20230622_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_time',
            field=models.TimeField(blank=True, default='12:00'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
