# Generated by Django 3.2.19 on 2023-07-19 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session_bookings', '0004_auto_20230628_0613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
    ]
