# Generated by Django 3.2.19 on 2023-07-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session_bookings', '0005_delete_personalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='todo',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
